require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'spec/dummy/bin/*'
    - '*.md'
    - lib/capriccio/parser/*
    - vendor/bundle/**/*

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/**/*.rb
    - capricc-io.gemspec

Metrics/BlockNesting:
  Max: 4

Layout/LineLength:
  Max: 120
  AllowURI: true

Metrics/MethodLength:
  CountComments: false
  Max: 80

Metrics/ModuleLength:
  Max: 250

Metrics/ClassLength:
  Max: 350

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect:  'map'
    collect!: 'map!'
    inject:   'reduce'
    find:     'detect'
    find_all: 'select'
    delete:   'gsub'

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Naming/FileName:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'no_comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'no_comma'

RSpec/MultipleExpectations:
  Max: 30

RSpec/ExampleLength:
  Max: 35

RSpec/FilePath:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
